import type { SupportedLanguage } from "../../onboarding/components/types";
import type { CareerCategory, EvidenceLevel } from "../../my-path/components/types";

export interface ExtendedTrade {
  id: string;
  category: CareerCategory;
  title: string;
  eligibilityEn: string;
  eligibilityHi: string;
  minQualification: "class_8" | "class_10" | "class_12" | "graduate";
  duration: string;
  govtFee: string;
  privateFee: string;
  startingPay: string;
  payGrowth: string;
  centerTypeEn: string;
  centerTypeHi: string;
  demandEn: string;
  demandHi: string;
  safetyEn: string;
  safetyHi: string;
  descriptionEn: string;
  descriptionHi: string;
  keySkills: string[];
  evidenceLevel: EvidenceLevel;
}

export function getAllTrades(lang: SupportedLanguage = "en"): readonly ExtendedTrade[] {
  if (lang === "hi") {
    return [
      {
        id: "electrician",
        category: "electrical",
        title: "इलेक्ट्रीशियन और सोलर तकनीशियन",
        eligibilityEn: "Class 10th Pass (Math & Science)",
        eligibilityHi: "10वीं पास (गणित और विज्ञान)",
        minQualification: "class_10",
        duration: "1–2 वर्ष (Govt ITI)",
        govtFee: "₹1,500 - ₹3,000",
        privateFee: "₹15,000 - ₹25,000",
        startingPay: "₹14,000 - ₹20,000 / माह",
        payGrowth: "2 वर्ष बाद ₹28,000+ प्रति माह",
        centerTypeEn: "Government ITI & PMKK",
        centerTypeHi: "राजकीय आईटीआई एवं पीएमकेके",
        demandEn: "High (Solar & Housing)",
        demandHi: "अत्यधिक मांग (सोलर एवं हाउसिंग)",
        safetyEn: "Safe with PPE (gloves, helmet)",
        safetyHi: "सुरक्षा उपकरणों के साथ पूर्णतः सुरक्षित",
        descriptionEn: "Domestic & industrial wiring, solar inverter installation and appliance testing.",
        descriptionHi: "घरेलू और औद्योगिक बिजली वायरिंग, सोलर इन्वर्टर इंस्टॉलेशन और उपकरण मरम्मत।",
        keySkills: ["वायरिंग", "सर्किट जांच", "सोलर पैनल रखरखाव"],
        evidenceLevel: "verified",
      },
      {
        id: "auto_technician",
        category: "auto",
        title: "ऑटोमोबाइल एवं ईवी मैकेनिक",
        eligibilityEn: "Class 10th Pass",
        eligibilityHi: "10वीं पास",
        minQualification: "class_10",
        duration: "1 वर्ष (ITI / PMKVY)",
        govtFee: "₹2,000",
        privateFee: "₹18,000",
        startingPay: "₹13,000 - ₹18,000 / माह",
        payGrowth: "ईवी विशेषज्ञता के साथ ₹30,000+",
        centerTypeEn: "PMKK & Auto Skill Council",
        centerTypeHi: "पीएमकेके एवं ऑटो स्किल काउंसिल",
        demandEn: "High (2-Wheeler & EV)",
        demandHi: "उच्च मांग (दोपहिया व ईवी)",
        safetyEn: "Regulated workshop protocols",
        safetyHi: "कार्यशाला में मानक सुरक्षा नियम",
        descriptionEn: "Vehicle engine diagnostics, brake tuning, battery testing, and EV motor repair.",
        descriptionHi: "वाहन इंजन डायग्नोस्टिक्स, ब्रेक ट्यूनिंग, बैटरी टेस्टिंग और ईवी मोटर मरम्मत।",
        keySkills: ["इंजन मरम्मत", "ब्रेक और सस्पेंशन", "इलेक्ट्रिक व्हीकल"],
        evidenceLevel: "verified",
      },
      {
        id: "rac_technician",
        category: "electrical",
        title: "आरएसी तकनीशियन (AC & फ्रिज मैकेनिक)",
        eligibilityEn: "Class 10th Pass",
        eligibilityHi: "10वीं पास",
        minQualification: "class_10",
        duration: "1–2 वर्ष (Govt ITI)",
        govtFee: "₹1,800",
        privateFee: "₹20,000",
        startingPay: "₹15,000 - ₹22,000 / माह",
        payGrowth: "समर सीजन एवं खुद की दुकान से ₹35,000+",
        centerTypeEn: "Govt ITI / Skill Center",
        centerTypeHi: "राजकीय आईटीआई / कौशल केंद्र",
        demandEn: "Very High (Domestic & Commercial)",
        demandHi: "अत्यधिक मांग (घरेलू और कमर्शियल)",
        safetyEn: "Gas safety training included",
        safetyHi: "गैस सेफ्टी और रेफ्रिजरेंट प्रशिक्षण शामिल",
        descriptionEn: "Installation and repair of Inverter ACs, deep freezers, and cold storages.",
        descriptionHi: "इन्वर्टर एसी, डीप फ्रीजर और कोल्ड स्टोरेज की इंस्टॉलेशन एवं मरम्मत।",
        keySkills: ["गैस चार्जिंग", "कंप्रेसर रिपेयर", "इन्वर्टर पीसीबी"],
        evidenceLevel: "verified",
      },
      {
        id: "fitter_machinist",
        category: "auto",
        title: "फिटर एवं खराद (Machinist / CNC Operator)",
        eligibilityEn: "Class 10th Pass",
        eligibilityHi: "10वीं पास",
        minQualification: "class_10",
        duration: "2 वर्ष (Govt ITI)",
        govtFee: "₹2,500",
        privateFee: "₹22,000",
        startingPay: "₹15,000 - ₹21,000 / माह",
        payGrowth: "सीएनसी ऑपरेटर के रूप में ₹32,000+",
        centerTypeEn: "Govt ITI & Industrial Units",
        centerTypeHi: "राजकीय आईटीआई एवं औद्योगिक इकाइयां",
        demandEn: "High in Manufacturing Clusters",
        demandHi: "मैन्युफैक्चरिंग हब में उच्च मांग",
        safetyEn: "Machine safety guards & PPE",
        safetyHi: "मशीन गार्ड और व्यक्तिगत सुरक्षा उपकरण",
        descriptionEn: "Precision metal cutting, assembling engineering parts, lathe and CNC operations.",
        descriptionHi: "सटीक धातु कटिंग, इंजीनियरिंग पार्ट्स असेंबलिंग और खराद/सीएनसी मशीन संचालन।",
        keySkills: ["लेथ मशीन", "सीएनसी कोडिंग", "प्रिसिजन फिटिंग"],
        evidenceLevel: "verified",
      },
      {
        id: "welder_fabricator",
        category: "construction",
        title: "वेल्डर एवं फैब्रिकेटर (Gas / Arc / TIG)",
        eligibilityEn: "Class 8th Pass",
        eligibilityHi: "8वीं पास",
        minQualification: "class_8",
        duration: "1 वर्ष (Govt ITI / NSDC)",
        govtFee: "₹1,200",
        privateFee: "₹12,000",
        startingPay: "₹16,000 - ₹24,000 / माह",
        payGrowth: "पाइपलाइन और निर्माण कार्य में ₹40,000+",
        centerTypeEn: "Govt ITI & Skill Hub",
        centerTypeHi: "राजकीय आईटीआई एवं कौशल हब",
        demandEn: "High (Infra & Construction)",
        demandHi: "उच्च मांग (इन्फ्रा एवं निर्माण)",
        safetyEn: "Eye shield and protective apron",
        safetyHi: "वेल्डिंग शील्ड और सुरक्षात्मक एप्रन",
        descriptionEn: "Metal joining, structural steel fabrication, pipeline welding and gate construction.",
        descriptionHi: "धातु वेल्डिंग, स्ट्रक्चरल स्टील फैब्रिकेशन और पाइपलाइन वेल्डिंग।",
        keySkills: ["आर्क वेल्डिंग", "टीआईजी वेल्डिंग", "स्ट्रक्चरल फैब्रिकेशन"],
        evidenceLevel: "verified",
      },
      {
        id: "data_entry_accounts",
        category: "digital",
        title: "कंप्यूटर ऑपरेटर (COPA) एवं जूनियर अकाउंटेंट",
        eligibilityEn: "Class 10th / 12th Pass",
        eligibilityHi: "10वीं / 12वीं पास",
        minQualification: "class_10",
        duration: "6–12 महीने (Govt ITI / NIELIT)",
        govtFee: "₹1,500 - ₹3,500",
        privateFee: "₹10,000",
        startingPay: "₹12,000 - ₹16,000 / माह",
        payGrowth: "टैली और जीएसटी अनुभव के साथ ₹25,000+",
        centerTypeEn: "District ITI & NIELIT Centers",
        centerTypeHi: "जिला आईटीआई एवं नाइलेट केंद्र",
        demandEn: "High in Banking & Local Retail",
        demandHi: "बैंकिंग, सीएससी एवं स्थानीय दुकानों में मांग",
        safetyEn: "Safe office environment",
        safetyHi: "पूर्णतः सुरक्षित इनडोर कार्यालय माहौल",
        descriptionEn: "Spreadsheets, data entry, Tally GST accounting, citizen service portal operator.",
        descriptionHi: "स्प्रेडशीट, डाटा एंट्री, टैली जीएसटी अकाउंटिंग और सीएससी सेवा पोर्टल संचालन।",
        keySkills: ["एमएस एक्सेल", "टैली ईआरपी", "टाइपिंग स्पीड"],
        evidenceLevel: "verified",
      },
      {
        id: "gda_healthcare",
        category: "healthcare",
        title: "जनरल ड्यूटी असिस्टेंट (नर्सिंग व पेशेंट केयर)",
        eligibilityEn: "Class 10th Pass",
        eligibilityHi: "10वीं पास",
        minQualification: "class_10",
        duration: "6 महीने (NSDC / Red Cross)",
        govtFee: "₹3,000 (मुफ्त वर्दी व किट)",
        privateFee: "₹14,000",
        startingPay: "₹13,000 - ₹18,000 / माह",
        payGrowth: "अस्पतालों में 2 वर्ष बाद ₹22,000+",
        centerTypeEn: "District Hospital Skilling Wing",
        centerTypeHi: "जिला अस्पताल स्किलिंग विंग",
        demandEn: "Constant High Demand",
        demandHi: "अस्पतालों एवं होम केयर में निरंतर मांग",
        safetyEn: "Sanitized hospital standards",
        safetyHi: "सैनिटाइज्ड अस्पताल सुरक्षा मानक",
        descriptionEn: "Vital signs monitoring, patient hygiene, medicine support, and emergency first aid.",
        descriptionHi: "मरीजों की देखभाल, बीपी/शुगर जांच, दवा वितरण में सहायता और प्राथमिक उपचार।",
        keySkills: ["प्राथमिक उपचार", "रोगी देखभाल", "मेडिकल रिकॉर्ड्स"],
        evidenceLevel: "verified",
      },
      {
        id: "plumbing_sanitary",
        category: "construction",
        title: "प्लंबर एवं सैनिटरी तकनीशियन",
        eligibilityEn: "Class 8th / 10th Pass",
        eligibilityHi: "8वीं / 10वीं पास",
        minQualification: "class_8",
        duration: "3–6 महीने (ITI / PMKVY)",
        govtFee: "₹1,000 (मुफ्त टूलकिट)",
        privateFee: "₹8,000",
        startingPay: "₹15,000 - ₹22,000 / माह",
        payGrowth: "स्वतंत्र ठेकेदारी से ₹35,000+",
        centerTypeEn: "PMKK & ITI",
        centerTypeHi: "पीएमकेके एवं आईटीआई",
        demandEn: "High (Urban & Rural Housing)",
        demandHi: "हर घर नल जल एवं हाउसिंग प्रोजेक्ट्स में मांग",
        safetyEn: "Field safety guidelines",
        safetyHi: "मानक फील्ड सुरक्षा नियम",
        descriptionEn: "Water supply pipeline installation, motor repairs, bathroom fitting and drainage.",
        descriptionHi: "पाइपलाइन इंस्टॉलेशन, मोटर मरम्मत, बाथरूम फिटिंग और ड्रेनेज रिपेयर।",
        keySkills: ["पाइप फिटिंग", "वॉटर पंप", "लीकेज डायग्नोसिस"],
        evidenceLevel: "verified",
      },
      {
        id: "tailoring_fashion",
        category: "craft",
        title: "सिलाई एवं परिधान निर्माण विशेषज्ञ (Sewing & Boutique)",
        eligibilityEn: "Class 8th Pass",
        eligibilityHi: "8वीं पास",
        minQualification: "class_8",
        duration: "6 महीने (Jan Shikshan Sansthan)",
        govtFee: "₹800",
        privateFee: "₹6,000",
        startingPay: "₹11,000 - ₹16,000 / माह",
        payGrowth: "बुटीक या गारमेंट यूनिट से ₹25,000+",
        centerTypeEn: "JSS Center & Women Skill Hub",
        centerTypeHi: "जन शिक्षण संस्थान एवं महिला कौशल केंद्र",
        demandEn: "Local & Self Employment",
        demandHi: "स्थानीय बाजार एवं खुद के बुटीक हेतु मांग",
        safetyEn: "Completely safe home/workshop",
        safetyHi: "घर या स्थानीय कार्यशाला में पूर्णतः सुरक्षित",
        descriptionEn: "Pattern cutting, sewing machine maintenance, garment stitching and designer embroidery.",
        descriptionHi: "कपड़ों की कटिंग, सिलाई मशीन संचालन, गारमेंट फिनिशिंग और डिजाइनिंग।",
        keySkills: ["पैटर्न मेकिंग", "मशीन संचालन", "गारमेंट फिनिशिंग"],
        evidenceLevel: "verified",
      },
    ];
  }

  return [
    {
      id: "electrician",
      category: "electrical",
      title: "Electrician & Solar Technician",
      eligibilityEn: "Class 10th Pass (Math & Science)",
      eligibilityHi: "10वीं पास (गणित और विज्ञान)",
      minQualification: "class_10",
      duration: "1–2 Years (Govt ITI)",
      govtFee: "₹1,500 - ₹3,000",
      privateFee: "₹15,000 - ₹25,000",
      startingPay: "₹14,000 - ₹20,000 / mo",
      payGrowth: "₹28,000+ after 2 yrs or self practice",
      centerTypeEn: "Government ITI & PMKK",
      centerTypeHi: "राजकीय आईटीआई एवं पीएमकेके",
      demandEn: "High (Solar & Housing)",
      demandHi: "अत्यधिक मांग (सोलर एवं हाउसिंग)",
      safetyEn: "Safe with standard PPE",
      safetyHi: "सुरक्षा उपकरणों के साथ पूर्णतः सुरक्षित",
      descriptionEn: "Domestic & industrial wiring, solar inverter installation and appliance testing.",
      descriptionHi: "घरेलू और औद्योगिक बिजली वायरिंग, सोलर इन्वर्टर इंस्टॉलेशन और उपकरण मरम्मत।",
      keySkills: ["Wiring & Circuits", "Solar Mounting", "Fault Testing"],
      evidenceLevel: "verified",
    },
    {
      id: "auto_technician",
      category: "auto",
      title: "Automobile & EV Service Mechanic",
      eligibilityEn: "Class 10th Pass",
      eligibilityHi: "10वीं पास",
      minQualification: "class_10",
      duration: "1 Year (ITI / PMKVY)",
      govtFee: "₹2,000",
      privateFee: "₹18,000",
      startingPay: "₹13,000 - ₹18,000 / mo",
      payGrowth: "Up to ₹30,000+ with EV diagnostic specialization",
      centerTypeEn: "PMKK & Auto Skill Council",
      centerTypeHi: "पीएमकेके एवं ऑटो स्किल काउंसिल",
      demandEn: "High (2-Wheeler & EV)",
      demandHi: "उच्च मांग (दोपहिया व ईवी)",
      safetyEn: "Regulated workshop protocols",
      safetyHi: "कार्यशाला में मानक सुरक्षा नियम",
      descriptionEn: "Vehicle engine diagnostics, brake tuning, battery testing, and EV motor repair.",
      descriptionHi: "वाहन इंजन डायग्नोस्टिक्स, ब्रेक ट्यूनिंग, बैटरी टेस्टिंग और ईवी मोटर मरम्मत।",
      keySkills: ["Engine Overhaul", "Brake Systems", "EV Battery Care"],
      evidenceLevel: "verified",
    },
    {
      id: "rac_technician",
      category: "electrical",
      title: "RAC Technician (AC & Refrigeration)",
      eligibilityEn: "Class 10th Pass",
      eligibilityHi: "10वीं पास",
      minQualification: "class_10",
      duration: "1–2 Years (Govt ITI)",
      govtFee: "₹1,800",
      privateFee: "₹20,000",
      startingPay: "₹15,000 - ₹22,000 / mo",
      payGrowth: "₹35,000+ in peak season or self shop",
      centerTypeEn: "Govt ITI / Skill Center",
      centerTypeHi: "राजकीय आईटीआई / कौशल केंद्र",
      demandEn: "Very High (Domestic & Commercial)",
      demandHi: "अत्यधिक मांग (घरेलू और कमर्शियल)",
      safetyEn: "Refrigerant & pressure safety trained",
      safetyHi: "गैस सेफ्टी और रेफ्रिजरेंट प्रशिक्षण शामिल",
      descriptionEn: "Installation and repair of Inverter ACs, deep freezers, and commercial cold storages.",
      descriptionHi: "इन्वर्टर एसी, डीप फ्रीजर और कोल्ड स्टोरेज की इंस्टॉलेशन एवं मरम्मत।",
      keySkills: ["Gas Charging", "Compressor Servicing", "PCB Diagnostics"],
      evidenceLevel: "verified",
    },
    {
      id: "fitter_machinist",
      category: "auto",
      title: "Fitter & CNC Machinist",
      eligibilityEn: "Class 10th Pass",
      eligibilityHi: "10वीं पास",
      minQualification: "class_10",
      duration: "2 Years (Govt ITI)",
      govtFee: "₹2,500",
      privateFee: "₹22,000",
      startingPay: "₹15,000 - ₹21,000 / mo",
      payGrowth: "₹32,000+ in manufacturing plants",
      centerTypeEn: "Govt ITI & Tool Rooms",
      centerTypeHi: "राजकीय आईटीआई एवं टूल रूम",
      demandEn: "High in Manufacturing Clusters",
      demandHi: "मैन्युफैक्चरिंग हब में उच्च मांग",
      safetyEn: "PPE & machine safety guards mandatory",
      safetyHi: "मशीन गार्ड और व्यक्तिगत सुरक्षा उपकरण",
      descriptionEn: "Precision metal cutting, assembling engineering parts, lathe and CNC operations.",
      descriptionHi: "सटीक धातु कटिंग, इंजीनियरिंग पार्ट्स असेंबलिंग और खराद/सीएनसी मशीन संचालन।",
      keySkills: ["Lathe Operation", "CNC Programming", "Precision Assembly"],
      evidenceLevel: "verified",
    },
    {
      id: "welder_fabricator",
      category: "construction",
      title: "Welder & Structural Fabricator",
      eligibilityEn: "Class 8th Pass",
      eligibilityHi: "8वीं पास",
      minQualification: "class_8",
      duration: "1 Year (Govt ITI / NSDC)",
      govtFee: "₹1,200",
      privateFee: "₹12,000",
      startingPay: "₹16,000 - ₹24,000 / mo",
      payGrowth: "₹40,000+ in infrastructure & pipeline projects",
      centerTypeEn: "Govt ITI & Skill Hub",
      centerTypeHi: "राजकीय आईटीआई एवं कौशल हब",
      demandEn: "High (Infra & Heavy Fabrication)",
      demandHi: "उच्च मांग (इन्फ्रा एवं निर्माण)",
      safetyEn: "Eye shield and leather apron standard",
      safetyHi: "वेल्डिंग शील्ड और सुरक्षात्मक एप्रन",
      descriptionEn: "Metal joining, structural steel fabrication, pipeline welding and gate construction.",
      descriptionHi: "धातु वेल्डिंग, स्ट्रक्चरल स्टील फैब्रिकेशन और पाइपलाइन वेल्डिंग।",
      keySkills: ["Arc Welding", "TIG Welding", "Blueprint Reading"],
      evidenceLevel: "verified",
    },
    {
      id: "data_entry_accounts",
      category: "digital",
      title: "Computer Operator (COPA) & Junior Accountant",
      eligibilityEn: "Class 10th / 12th Pass",
      eligibilityHi: "10वीं / 12वीं पास",
      minQualification: "class_10",
      duration: "6–12 Months (Govt ITI / NIELIT)",
      govtFee: "₹1,500 - ₹3,500",
      privateFee: "₹10,000",
      startingPay: "₹12,000 - ₹16,000 / mo",
      payGrowth: "₹25,000+ with GST accounting experience",
      centerTypeEn: "District ITI & NIELIT Centers",
      centerTypeHi: "जिला आईटीआई एवं नाइलेट केंद्र",
      demandEn: "High in Banking & Local Retail",
      demandHi: "बैंकिंग, सीएससी एवं स्थानीय दुकानों में मांग",
      safetyEn: "Safe indoor office environment",
      safetyHi: "पूर्णतः सुरक्षित इनडोर कार्यालय माहौल",
      descriptionEn: "Spreadsheets, data entry, Tally GST accounting, citizen service portal operator.",
      descriptionHi: "स्प्रेडशीट, डाटा एंट्री, टैली जीएसटी अकाउंटिंग और सीएससी सेवा पोर्टल संचालन।",
      keySkills: ["MS Excel", "Tally ERP", "Typing Speed"],
      evidenceLevel: "verified",
    },
    {
      id: "gda_healthcare",
      category: "healthcare",
      title: "General Duty Assistant (Nursing & Patient Care)",
      eligibilityEn: "Class 10th Pass",
      eligibilityHi: "10वीं पास",
      minQualification: "class_10",
      duration: "6 Months (NSDC / Red Cross)",
      govtFee: "₹3,000 (Free uniform & kit)",
      privateFee: "₹14,000",
      startingPay: "₹13,000 - ₹18,000 / mo",
      payGrowth: "₹22,000+ after 2 years in hospitals",
      centerTypeEn: "District Hospital Skilling Wing",
      centerTypeHi: "जिला अस्पताल स्किलिंग विंग",
      demandEn: "Constant High Demand",
      demandHi: "अस्पतालों एवं होम केयर में निरंतर मांग",
      safetyEn: "Sanitized hospital standards",
      safetyHi: "सैनिटाइज्ड अस्पताल सुरक्षा मानक",
      descriptionEn: "Vital signs monitoring, patient hygiene, medicine support, and emergency first aid.",
      descriptionHi: "मरीजों की देखभाल, बीपी/शुगर जांच, दवा वितरण में सहायता और प्राथमिक उपचार।",
      keySkills: ["First Aid", "Patient Monitoring", "Hygiene Protocols"],
      evidenceLevel: "verified",
    },
    {
      id: "plumbing_sanitary",
      category: "construction",
      title: "Plumbing & Sanitary Technician",
      eligibilityEn: "Class 8th / 10th Pass",
      eligibilityHi: "8वीं / 10वीं पास",
      minQualification: "class_8",
      duration: "3–6 Months (ITI / PMKVY)",
      govtFee: "₹1,000 (Free toolkit support)",
      privateFee: "₹8,000",
      startingPay: "₹15,000 - ₹22,000 / mo",
      payGrowth: "₹35,000+ in self-contracting",
      centerTypeEn: "PMKK & ITI",
      centerTypeHi: "पीएमकेके एवं आईटीआई",
      demandEn: "High (Urban & Rural Housing)",
      demandHi: "हर घर नल जल एवं हाउसिंग प्रोजेक्ट्स में मांग",
      safetyEn: "Field safety guidelines",
      safetyHi: "मानक फील्ड सुरक्षा नियम",
      descriptionEn: "Water supply pipeline installation, motor repairs, bathroom fitting and drainage.",
      descriptionHi: "पाइपलाइन इंस्टॉलेशन, मोटर मरम्मत, बाथरूम फिटिंग और ड्रेनेज रिपेयर।",
      keySkills: ["Pipe Fitting", "Water Pumps", "Leakage Diagnostics"],
      evidenceLevel: "verified",
    },
    {
      id: "tailoring_fashion",
      category: "craft",
      title: "Sewing & Garment Construction Specialist",
      eligibilityEn: "Class 8th Pass",
      eligibilityHi: "8वीं पास",
      minQualification: "class_8",
      duration: "6 Months (Jan Shikshan Sansthan)",
      govtFee: "₹800",
      privateFee: "₹6,000",
      startingPay: "₹11,000 - ₹16,000 / mo",
      payGrowth: "₹25,000+ in self-owned boutique",
      centerTypeEn: "JSS Center & Women Skill Hub",
      centerTypeHi: "जन शिक्षण संस्थान एवं महिला कौशल केंद्र",
      demandEn: "Local & Self Employment",
      demandHi: "स्थानीय बाजार एवं खुद के बुटीक हेतु मांग",
      safetyEn: "Completely safe home/workshop",
      safetyHi: "घर या स्थानीय कार्यशाला में पूर्णतः सुरक्षित",
      descriptionEn: "Pattern cutting, sewing machine maintenance, garment stitching and designer embroidery.",
      descriptionHi: "कपड़ों की कटिंग, सिलाई मशीन संचालन, गारमेंट फिनिशिंग और डिजाइनिंग।",
      keySkills: ["Pattern Making", "Machine Handling", "Garment Finishing"],
      evidenceLevel: "verified",
    },
  ];
}
