import type { DocumentItem, AdmissionStep } from "./types";

export const initialDocuments: DocumentItem[] = [
  {
    id: "aadhaar",
    titleEn: "Aadhaar Card (Front & Back)",
    titleHi: "आधार कार्ड (आगे और पीछे का भाग)",
    descriptionEn: "Required for government verification and scholarship benefit link.",
    descriptionHi: "सरकारी सत्यापन और छात्रवृत्ति लिंक करने के लिए अनिवार्य।",
    required: true,
    status: "ready",
    exampleEn: "Clear photo or PDF copy",
    exampleHi: "साफ फोटो या पीडीएफ प्रति",
  },
  {
    id: "marksheet",
    titleEn: "10th / 12th Class Marksheet",
    titleHi: "10वीं / 12वीं की अंकतालिका (मार्कशीट)",
    descriptionEn: "Proves eligibility for technical ITI & diploma trades.",
    descriptionHi: "तकनीकी आईटीआई और डिप्लोमा कोर्स में दाखिले के लिए जरूरी।",
    required: true,
    status: "ready",
    exampleEn: "Original marksheet photo or DigiLocker download",
    exampleHi: "मूल मार्कशीट की फोटो या डिजिलॉकर प्रति",
  },
  {
    id: "photos",
    titleEn: "Passport Size Photographs (4 Copies)",
    titleHi: "पासपोर्ट साइज रंगीन फोटो (4 प्रतियां)",
    descriptionEn: "Needed for student ID card and institute registration form.",
    descriptionHi: "छात्र पहचान पत्र और संस्थान पंजीकरण फॉर्म के लिए आवश्यक।",
    required: true,
    status: "pending",
    exampleEn: "Recent colored photo with white background",
    exampleHi: "हाल ही में खिंचवाई गई सफेद बैकग्राउंड वाली फोटो",
  },
  {
    id: "caste_domicile",
    titleEn: "Caste / Domicile Certificate (Optional)",
    titleHi: "जाति / निवास प्रमाण पत्र (वैकल्पिक)",
    descriptionEn: "Required to claim government fee exemption & stipends.",
    descriptionHi: "सरकारी फीस में छूट और मासिक छात्रवृत्ति प्राप्त करने के लिए।",
    required: false,
    status: "optional",
    exampleEn: "State portal issued certificate",
    exampleHi: "राज्य सरकार द्वारा जारी प्रमाण पत्र",
  },
];

export const admissionTimeline: AdmissionStep[] = [
  {
    stepNumber: 1,
    titleEn: "Online Application & Form Submission",
    titleHi: "ऑनलाइन आवेदन एवं फॉर्म भरना",
    dateEn: "Open Now (Deadline: 25 Oct)",
    dateHi: "आवेदन जारी (अंतिम तिथि: 25 अक्टूबर)",
    status: "active",
    actionTextEn: "Saathi Form Assistant",
    actionTextHi: "साथी फॉर्म सहायक",
  },
  {
    stepNumber: 2,
    titleEn: "Document Verification at Nearest ITI Center",
    titleHi: "नजदीकी आईटीआई केंद्र पर मूल दस्तावेज जांच",
    dateEn: "28 Oct - 05 Nov",
    dateHi: "28 अक्टूबर - 05 नवंबर",
    status: "upcoming",
    actionTextEn: "View Checklist",
    actionTextHi: "चेकलिस्ट देखें",
  },
  {
    stepNumber: 3,
    titleEn: "Merit List & Seat Allotment",
    titleHi: "मेरिट सूची एवं सीट आवंटन",
    dateEn: "10 Nov",
    dateHi: "10 नवंबर",
    status: "upcoming",
    actionTextEn: "Check Status",
    actionTextHi: "स्थिति जांचें",
  },
  {
    stepNumber: 4,
    titleEn: "Fee Payment (₹1,500) & Batch Orientation",
    titleHi: "फीस जमा (₹1,500) एवं क्लास की शुरुआत",
    dateEn: "15 Nov",
    dateHi: "15 नवंबर",
    status: "upcoming",
    actionTextEn: "Fee Guidance",
    actionTextHi: "फीस ब्यौरा",
  },
];
