import type { OnboardingStep, SupportedLanguage } from "./types";

export function getOnboardingSteps(
  lang: SupportedLanguage = "en",
): readonly OnboardingStep[] {
  if (lang === "hi") {
    return [
      {
        id: "language",
        label: "भाषा चुनें",
        question: "आप किस भाषा में बात करना और पढ़ना पसंद करेंगे?",
        whyExplanation: "ताकि आप और आपका परिवार हर बात आसानी से समझ सकें।",
        type: "single",
        options: [
          { id: "hi", label: "हिन्दी", description: "सरल हिन्दी में बातचीत" },
          { id: "en", label: "English", description: "Simple English guidance" },
        ],
        listenText: "अपनी पसंदीदा भाषा चुनें।",
      },
      {
        id: "basics",
        label: "मूल जानकारी",
        question: "आपका पूरा नाम, फोन नंबर और गृह जिला क्या है?",
        whyExplanation: "काउंसलर से मुफ्त फोन परामर्श और आपके नजदीकी सरकारी आईटीआई खोजने के लिए।",
        type: "basics",
        listenText: "अपना नाम, मोबाइल नंबर और अपना जिला दर्ज करें।",
      },
      {
        id: "education",
        label: "शिक्षा और अनुभव",
        question: "आपकी उच्चतम शिक्षा क्या है?",
        whyExplanation: "ताकि आपको वही कोर्स दिखाए जाएं जिनमें आप सीधे दाखिला ले सकें।",
        type: "single",
        options: [
          { id: "class_8", label: "8वीं पास" },
          { id: "class_10", label: "10वीं पास (मैट्रिक)" },
          { id: "class_12", label: "12वीं पास" },
          { id: "iti_diploma", label: "आईटीआई / डिप्लोमा" },
          { id: "graduate", label: "ग्रेजुएट / कोई अन्य डिग्री" },
          { id: "other", label: "अन्य डिग्री या पढ़ाई बीच में छूटी" },
        ],
        listenText: "अपनी पिछली कक्षा या पढ़ाई का स्तर चुनें।",
      },
      {
        id: "interests",
        label: "आपकी रुचियां",
        question: "आपको किस तरह के काम में सबसे ज्यादा मजा आता है?",
        whyExplanation: "साथी ऐसे काम ढूंढेगा जो आपकी पसंद के अनुकूल हों।",
        type: "multi",
        maxSelections: 5,
        options: [
          { id: "machines", label: "मशीन और उपकरण ठीक करना" },
          { id: "electrical", label: "बिजली और वायरिंग का काम" },
          { id: "healthcare", label: "मरीजों की सेवा और प्राथमिक चिकित्सा" },
          { id: "vehicles", label: "गाड़ियों की मरम्मत और ऑटोमोबाइल" },
          { id: "computers", label: "कंप्यूटर और डाटा एंट्री" },
          { id: "craft_tailoring", label: "सिलाई, बुनाई और हस्तकला" },
          { id: "construction", label: "निर्माण और प्लंबिंग" },
        ],
        listenText: "अपनी पसंद के काम चुनें। आप 5 विकल्प तक चुन सकते हैं।",
      },
      {
        id: "workPreferences",
        label: "काम करने का तरीका",
        question: "आप किस तरह काम करना चाहते हैं?",
        whyExplanation: "ताकि परिवार की सुविधा और काम की दूरी का पूरा ध्यान रहे।",
        type: "single",
        options: [
          { id: "near_home", label: "घर के नजदीक काम", description: "अपने गाँव या जिले के पास" },
          { id: "willing_relocate", label: "दूसरे शहर जाने को तैयार", description: "अच्छे वेतन और सीखने के लिए" },
          { id: "both", label: "दोनों विकल्प खुले हैं" },
        ],
        listenText: "चुनें कि क्या आप घर के पास काम चाहते हैं या बाहर जा सकते हैं।",
      },
      {
        id: "goals",
        label: "उम्मीदें और जरूरतें",
        question: "आपके लिए सबसे महत्वपूर्ण क्या है?",
        whyExplanation: "यह हमें जल्दी नौकरी और परिवार की आर्थिक सहायता में सही तालमेल बिठाने में मदद करता है।",
        type: "single",
        isOptional: true,
        options: [
          { id: "fast_earning", label: "जल्दी से कमाई शुरू करना (कम समय का कोर्स)" },
          { id: "higher_growth", label: "भविष्य में बड़ा वेतन और स्थायी करियर" },
          { id: "own_shop", label: "खुद की दुकान या काम शुरू करना" },
          { id: "unsure", label: "अभी निश्चित नहीं / साथी मदद करे" },
        ],
        listenText: "अपनी सबसे बड़ी प्राथमिकता चुनें।",
      },
      {
        id: "resume",
        label: "बायोडाटा / प्रमाणपत्र",
        question: "क्या आपके पास पहले से बायोडाटा (Resume) या कोई सर्टिफिकेट है?",
        whyExplanation: "अगर है, तो साथी आपकी पिछली जानकारी अपने आप जोड़ लेगा। पासवर्ड कभी नहीं मांगा जाएगा।",
        type: "upload",
        isOptional: true,
        options: [
          { id: "upload_now", label: "फोन से फोटो या पीडीएफ अपलोड करें" },
          { id: "skip", label: "अभी नहीं है / बाद में जोड़ेंगे" },
        ],
        listenText: "यदि आपके पास बायोडाटा है तो अपलोड करें, या छोड़ दें।",
      },
      {
        id: "portals",
        label: "जॉब प्रोफाइल",
        question: "क्या आप किसी ऑनलाइन पोर्टल (NCS, e-Shram, Apna आदि) पर पंजीकृत हैं?",
        whyExplanation: "यह पूरी तरह वैकल्पिक है। हम कभी भी किसी पोर्टल का पासवर्ड नहीं मांगते।",
        type: "single",
        isOptional: true,
        options: [
          { id: "ncs", label: "नेशनल करियर सर्विस (NCS)" },
          { id: "eshram", label: "ई-श्रम (e-Shram)" },
          { id: "apna", label: "अपना ऐप (Apna / WorkIndia)" },
          { id: "none", label: "कोई प्रोफाइल नहीं है / पता नहीं" },
        ],
        listenText: "यदि आप किसी सरकारी या प्राइवेट जॉब पोर्टल पर जुड़े हैं तो चुनें।",
      },
    ];
  }

  return [
    {
      id: "language",
      label: "Choose Language",
      question: "Which language do you prefer to speak and read?",
      whyExplanation: "So you and your family can easily understand every guidance step.",
      type: "single",
      options: [
        { id: "en", label: "English", description: "Simple English guidance" },
        { id: "hi", label: "हिन्दी", description: "सरल हिन्दी में बातचीत" },
      ],
      listenText: "Choose your preferred language.",
    },
    {
      id: "basics",
      label: "Basic Details",
      question: "What is your full name, phone number, and home district?",
      whyExplanation: "For free counsellor support and to locate verified training institutes near you.",
      type: "basics",
      listenText: "Enter your full name, mobile number, and district.",
    },
    {
      id: "education",
      label: "Education",
      question: "What is your highest qualification?",
      whyExplanation: "To show programs and trades where you are directly eligible.",
      type: "single",
      options: [
        { id: "class_8", label: "Class 8 Pass" },
        { id: "class_10", label: "Class 10 Pass (Matric)" },
        { id: "class_12", label: "Class 12 Pass" },
        { id: "iti_diploma", label: "ITI or Diploma completed" },
        { id: "graduate", label: "Graduate / Other Degree" },
        { id: "other", label: "Other degree or discontinued study" },
      ],
      listenText: "Select your highest completed grade or qualification.",
    },
    {
      id: "interests",
      label: "Your Interests",
      question: "What kind of practical work do you enjoy doing?",
      whyExplanation: "Saathi suggests trades matching your day-to-day energy and interest.",
      type: "multi",
      maxSelections: 5,
      options: [
        { id: "machines", label: "Fixing tools & machinery" },
        { id: "electrical", label: "Electrical wiring & appliances" },
        { id: "healthcare", label: "Patient care & first aid" },
        { id: "vehicles", label: "Vehicle & motor repair" },
        { id: "computers", label: "Computers & data entry" },
        { id: "craft_tailoring", label: "Tailoring & craft work" },
        { id: "construction", label: "Plumbing & building work" },
      ],
      listenText: "Select practical trades you like. You can pick up to 5.",
    },
    {
      id: "workPreferences",
      label: "Work Style",
      question: "Where do you prefer to work?",
      whyExplanation: "Helps balance family convenience with career opportunities.",
      type: "single",
      options: [
        { id: "near_home", label: "Near home", description: "In your home district" },
        { id: "willing_relocate", label: "Open to relocate", description: "For better pay and growth" },
        { id: "both", label: "Open to both options" },
      ],
      listenText: "Choose whether you prefer working locally or can travel.",
    },
    {
      id: "goals",
      label: "Goals & Timeline",
      question: "What is your main goal right now?",
      whyExplanation: "Helps tailor course duration and budget recommendations.",
      type: "single",
      isOptional: true,
      options: [
        { id: "fast_earning", label: "Start earning quickly (short course)" },
        { id: "higher_growth", label: "Long-term career growth & higher pay" },
        { id: "own_shop", label: "Start own small workshop / business" },
        { id: "unsure", label: "Unsure / Want Saathi's suggestion" },
      ],
      listenText: "Pick what matters most to you right now.",
    },
    {
      id: "resume",
      label: "Resume / Biodata",
      question: "Do you have a biodata or any certificate?",
      whyExplanation: "Saathi can read it to save your time. We never ask for portal passwords.",
      type: "upload",
      isOptional: true,
      options: [
        { id: "upload_now", label: "Upload photo or PDF from phone" },
        { id: "skip", label: "I do not have one / Add later" },
      ],
      listenText: "Upload your resume if available, or skip for now.",
    },
    {
      id: "portals",
      label: "Online Profiles",
      question: "Are you registered on any career portal (NCS, e-Shram, Apna)?",
      whyExplanation: "Optional. We never ask for passwords or take over your account.",
      type: "single",
      isOptional: true,
      options: [
        { id: "ncs", label: "National Career Service (NCS)" },
        { id: "eshram", label: "e-Shram" },
        { id: "apna", label: "Apna / WorkIndia" },
        { id: "none", label: "No profile / I don't know" },
      ],
      listenText: "Select any existing job portal you use, or choose none.",
    },
  ];
}
