import type { CareerPath } from "./types";
import type { SupportedLanguage } from "../../onboarding/components/types";

export function getCareerPaths(lang: SupportedLanguage = "en"): readonly CareerPath[] {
  if (lang === "hi") {
    return [
      {
        id: "electrician",
        category: "electrical",
        title: "इलेक्ट्रीशियन और सोलर तकनीशियन",
        matchScore: 92,
        workStyle: "व्यावहारिक एवं तकनीकी कार्य · 6–12 महीने प्रशिक्षण",
        duration: "6 महीने से 1 साल",
        totalCost: "सरकारी आईटीआई: ₹1,500 - ₹3,000 | प्राइवेट: ₹12,000",
        startingPay: "₹14,000 - ₹20,000 प्रति माह",
        payGrowth: "2 वर्ष के अनुभव के बाद ₹28,000+ प्रति माह या स्वयं का काम",
        verifiedCentresCount: 3,
        nearestCenter: "राजकीय औद्योगिक प्रशिक्षण संस्थान (Govt ITI)",
        travelDistance: "8 किमी दूर (स्थानीय बस उपलब्ध)",
        safetyRating: "सुरक्षा उपकरणों (हेलमेट, दस्ताने) के साथ सुरक्षित",
        dayInTheLife:
          "घरेलू और औद्योगिक बिजली वायरिंग, सोलर पैनल इंस्टॉलेशन, और फॉल्ट रिपेयरिंग।",
        whyFit:
          "आपकी बिजली और व्यावहारिक उपकरणों में रुचि और 10वीं/12वीं योग्यता के अनुकूल।",
        questionsAnswered: "परिवार के 5 में से 4 सवालों के जवाब उपलब्ध",
        evidenceLevel: "verified",
        keySkills: ["वायरिंग", "सर्किट जांच", "सोलर पैनल रखरखाव"],
      },
      {
        id: "auto_technician",
        category: "auto",
        title: "ऑटोमोबाइल एवं ईवी मैकेनिक",
        matchScore: 85,
        workStyle: "गाड़ियों की मरम्मत एवं डायग्नोस्टिक्स · 1 साल कोर्स",
        duration: "1 वर्ष (ITI / PMKVY)",
        totalCost: "सरकारी संस्थान: ₹2,000 | प्राइवेट: ₹15,000",
        startingPay: "₹13,000 - ₹18,000 प्रति माह",
        payGrowth: "ईवी सर्विसिंग में 3 साल बाद ₹30,000+ तक अवसर",
        verifiedCentresCount: 2,
        nearestCenter: "प्रधानमंत्री कौशल केंद्र (PMKK Center)",
        travelDistance: "12 किमी दूर",
        safetyRating: "कार्यशाला में मानक सुरक्षा नियमों के साथ काम",
        dayInTheLife:
          "दोपहिया एवं चार पहिया वाहनों का इंजन काम, सर्विसिंग एवं इलेक्ट्रॉनिक जांच।",
        whyFit: "वाहनों और औजारों के साथ व्यावहारिक काम करने की इच्छा के अनुकूल।",
        questionsAnswered: "परिवार के 5 में से 3 सवालों के जवाब उपलब्ध",
        evidenceLevel: "verified",
        keySkills: ["इंजन मरम्मत", "ब्रेक और सस्पेंशन", "इलेक्ट्रिक व्हीकल बेसिक्स"],
      },
      {
        id: "data_entry_accounts",
        category: "digital",
        title: "कंप्यूटर ऑपरेटर एवं जूनियर अकाउंटेंट",
        matchScore: 78,
        workStyle: "कार्यालय/दफ्तर का काम · 3–6 महीने डिप्लोमा",
        duration: "3 से 6 महीने (Tally + Office)",
        totalCost: "₹4,000 - ₹8,000 (स्कॉलरशिप उपलब्ध)",
        startingPay: "₹12,000 - ₹16,000 प्रति माह",
        payGrowth: "अकाउंटेंसी और जीएसटी ज्ञान के साथ ₹25,000+",
        verifiedCentresCount: 4,
        nearestCenter: "जिला कंप्यूटर प्रशिक्षण केंद्र",
        travelDistance: "4 किमी दूर (कस्बा मुख्य बाजार)",
        safetyRating: "सुरक्षित इनडोर कार्यालय वातावरण",
        dayInTheLife:
          "दैनिक बिलिंग, एक्सेल में रिकॉर्ड संधारण, डाटा एंट्री और ग्राहक सहायता।",
        whyFit: "कार्यालय आधारित काम और स्नातक/12वीं पृष्ठभूमि के अनुकूल।",
        questionsAnswered: "परिवार के 5 में से 5 सवालों के जवाब उपलब्ध",
        evidenceLevel: "guidance",
        keySkills: ["एमएस एक्सेल", "टैली / जीएसटी बिलिंग", "टाइपिंग कौशल"],
      },
      {
        id: "gda_healthcare",
        category: "healthcare",
        title: "जनरल ड्यूटी असिस्टेंट (अस्पताल नर्सिंग सहायक)",
        matchScore: 74,
        workStyle: "स्वास्थ्य सेवा एवं रोगी देखभाल · 6 महीने कोर्स",
        duration: "6 महीने (NSDC / Red Cross)",
        totalCost: "₹3,000 - ₹6,000 (सरकारी सहायता उपलब्ध)",
        startingPay: "₹13,000 - ₹18,000 प्रति माह",
        payGrowth: "अस्पतालों में 2 वर्ष बाद ₹22,000+ और स्थायी नौकरी",
        verifiedCentresCount: 3,
        nearestCenter: "जिला अस्पताल स्किलिंग विंग",
        travelDistance: "6 किमी दूर",
        safetyRating: "स्वच्छ एवं सुरक्षित अस्पताल परिसर",
        dayInTheLife: "मरीजों की देखभाल, बीपी/शुगर जांच, और डॉक्टर की सहायता।",
        whyFit: "दूसरों की मदद करने और स्वास्थ्य क्षेत्र में सम्मानजनक काम के अनुकूल।",
        questionsAnswered: "परिवार के 5 में से 5 सवालों के जवाब उपलब्ध",
        evidenceLevel: "verified",
        keySkills: ["प्राथमिक उपचार", "रोगी देखभाल", "मेडिकल रिकॉर्ड्स"],
      },
      {
        id: "plumbing_sanitary",
        category: "construction",
        title: "प्लंबर एवं सैनिटरी तकनीशियन",
        matchScore: 72,
        workStyle: "घरों और इमारतों में पाइपलाइन कार्य · 3–6 महीने",
        duration: "3 से 6 महीने (ITI / PMKVY)",
        totalCost: "₹1,000 - ₹2,500 (मुफ्त टूलकिट सहायता)",
        startingPay: "₹15,000 - ₹22,000 प्रति माह",
        payGrowth: "स्वतंत्र ठेकेदारी से ₹35,000+ प्रति माह की संभावना",
        verifiedCentresCount: 2,
        nearestCenter: "कौशल विकास केंद्र",
        travelDistance: "9 किमी दूर",
        safetyRating: "फील्ड कार्य, मानक सुरक्षा निर्देश लागू",
        dayInTheLife: "पाइप फिटिंग, लीकेज रिपेयर, मोटर और वाटर पंप इंस्टॉलेशन।",
        whyFit: "कम समय में तुरंत अच्छी कमाई और खुद का काम शुरू करने के अनुकूल।",
        questionsAnswered: "परिवार के 5 में से 4 सवालों के जवाब उपलब्ध",
        evidenceLevel: "verified",
        keySkills: ["पाइप फिटिंग", "वॉटर पंप", "लीकेज डायग्नोसिस"],
      },
      {
        id: "tailoring_fashion",
        category: "craft",
        title: "सिलाई एवं परिधान निर्माण विशेषज्ञ",
        matchScore: 70,
        workStyle: "सिलाई, डिजाइन एवं बुटीक कार्य · 6 महीने",
        duration: "6 महीने (Jan Shikshan Sansthan)",
        totalCost: "₹1,000 (सरकारी सब्सिडी)",
        startingPay: "₹11,000 - ₹16,000 प्रति माह",
        payGrowth: "घर से बुटीक या गारमेंट यूनिट से ₹25,000+",
        verifiedCentresCount: 3,
        nearestCenter: "जन शिक्षण संस्थान केंद्र",
        travelDistance: "3 किमी दूर",
        safetyRating: "घर या स्थानीय कार्यशाला में पूर्णतः सुरक्षित",
        dayInTheLife: "कपड़ों की कटिंग, सिलाई मशीन संचालन, और डिजाइनिंग।",
        whyFit: "घर के पास या स्वरोजगार शुरू करने की सुविधा के अनुकूल।",
        questionsAnswered: "परिवार के 5 में से 5 सवालों के जवाब उपलब्ध",
        evidenceLevel: "guidance",
        keySkills: ["पैटर्न मेकिंग", "मशीन संचालन", "गारमेंट फिनिशिंग"],
      },
    ];
  }

  return [
    {
      id: "electrician",
      category: "electrical",
      title: "Electrician & Solar Technician",
      matchScore: 92,
      workStyle: "Hands-on & Technical · 6–12 months training",
      duration: "6 to 12 months",
      totalCost: "Govt ITI: ₹1,500 - ₹3,000 | Private: ₹12,000",
      startingPay: "₹14,000 - ₹20,000 / month",
      payGrowth: "₹28,000+ after 2 years or start own electrical services",
      verifiedCentresCount: 3,
      nearestCenter: "Government ITI Institute",
      travelDistance: "8 km away (Direct bus available)",
      safetyRating: "Safe with standard PPE (gloves, insulated tools)",
      dayInTheLife:
        "Wiring installations, home appliance diagnostics, solar panel mounting and circuit repair.",
      whyFit:
        "Matches your interest in fixing tools & electrical wiring with local job demand.",
      questionsAnswered: "4 of 5 family questions answered",
      evidenceLevel: "verified",
      keySkills: ["Wiring & Circuits", "Safety Testing", "Solar Maintenance"],
    },
    {
      id: "auto_technician",
      category: "auto",
      title: "Automobile & EV Service Mechanic",
      matchScore: 85,
      workStyle: "Vehicle repair & workshop · 1 year course",
      duration: "1 Year (ITI / PMKVY)",
      totalCost: "Govt center: ₹2,000 | Private: ₹15,000",
      startingPay: "₹13,000 - ₹18,000 / month",
      payGrowth: "Up to ₹30,000+ with EV diagnostic specialization",
      verifiedCentresCount: 2,
      nearestCenter: "Pradhan Mantri Kaushal Kendra (PMKK)",
      travelDistance: "12 km away",
      safetyRating: "Standard workshop safety protocols",
      dayInTheLife:
        "Servicing two-wheelers and four-wheelers, brake tuning, oil changes, and EV battery testing.",
      whyFit: "Matches your preference for mechanical and workshop-based work.",
      questionsAnswered: "3 of 5 family questions answered",
      evidenceLevel: "verified",
      keySkills: ["Engine Diagnostics", "Braking Systems", "EV Basics"],
    },
    {
      id: "data_entry_accounts",
      category: "digital",
      title: "Computer Operator & Office Assistant",
      matchScore: 78,
      workStyle: "Office-based work · 3–6 months diploma",
      duration: "3 to 6 months (Tally + Office suite)",
      totalCost: "₹4,000 - ₹8,000 (Fee subsidy available)",
      startingPay: "₹12,000 - ₹16,000 / month",
      payGrowth: "₹25,000+ with GST and bookkeeping experience",
      verifiedCentresCount: 4,
      nearestCenter: "District Skill Center",
      travelDistance: "4 km away (Town center)",
      safetyRating: "Completely safe indoor office environment",
      dayInTheLife:
        "Daily billing, record keeping in spreadsheets, customer support and document filing.",
      whyFit: "Good fit for office preference and secondary/college qualification.",
      questionsAnswered: "5 of 5 family questions answered",
      evidenceLevel: "guidance",
      keySkills: ["MS Excel", "Tally / GST", "Data Verification"],
    },
    {
      id: "gda_healthcare",
      category: "healthcare",
      title: "General Duty Assistant (Healthcare / Hospital)",
      matchScore: 74,
      workStyle: "Patient Care & Nursing Support · 6 months course",
      duration: "6 months (NSDC / Red Cross)",
      totalCost: "₹3,000 - ₹6,000 (Govt subsidy available)",
      startingPay: "₹13,000 - ₹18,000 / month",
      payGrowth: "₹22,000+ after 2 years in private/govt hospitals",
      verifiedCentresCount: 3,
      nearestCenter: "District Hospital Training Wing",
      travelDistance: "6 km away",
      safetyRating: "Clean and safe hospital environment",
      dayInTheLife:
        "Patient monitoring, taking vital signs, first aid and assisting nursing staff.",
      whyFit: "Good fit for serving people with stable hospital employment.",
      questionsAnswered: "5 of 5 family questions answered",
      evidenceLevel: "verified",
      keySkills: ["First Aid", "Patient Care", "Medical Records"],
    },
    {
      id: "plumbing_sanitary",
      category: "construction",
      title: "Plumbing & Sanitary Technician",
      matchScore: 72,
      workStyle: "Pipeline & installation work · 3–6 months",
      duration: "3 to 6 months (ITI / PMKVY)",
      totalCost: "₹1,000 - ₹2,500 (Free toolkit support)",
      startingPay: "₹15,000 - ₹22,000 / month",
      payGrowth: "₹35,000+ per month through independent contracting",
      verifiedCentresCount: 2,
      nearestCenter: "Rural Skill Center",
      travelDistance: "9 km away",
      safetyRating: "Field work with standard safety guidelines",
      dayInTheLife:
        "Fitting pipes, repairing leaks, installing water pumps and drainage fittings.",
      whyFit: "Great for quick earning and starting independent local work.",
      questionsAnswered: "4 of 5 family questions answered",
      evidenceLevel: "verified",
      keySkills: ["Pipe Fitting", "Water Pumps", "Leakage Diagnostics"],
    },
    {
      id: "tailoring_fashion",
      category: "craft",
      title: "Apparel & Tailoring Specialist",
      matchScore: 70,
      workStyle: "Stitching & Boutique craft · 6 months",
      duration: "6 months (Jan Shikshan Sansthan)",
      totalCost: "₹1,000 (Govt subsidized)",
      startingPay: "₹11,000 - ₹16,000 / month",
      payGrowth: "₹25,000+ running a boutique or garment contract unit",
      verifiedCentresCount: 3,
      nearestCenter: "Jan Shikshan Sansthan Center",
      travelDistance: "3 km away",
      safetyRating: "Completely safe home or workshop setting",
      dayInTheLife:
        "Pattern drafting, operating industrial sewing machines, alterations and custom design.",
      whyFit: "Flexible work suitable for home-based self-employment or factory roles.",
      questionsAnswered: "5 of 5 family questions answered",
      evidenceLevel: "guidance",
      keySkills: ["Pattern Drafting", "Machine Operation", "Garment Finishing"],
    },
  ];
}
