import type { FamilyCallbackLead, SentimentOverviewMetric, TradeEditorItem } from "./types";

export const initialSentimentMetrics: SentimentOverviewMetric[] = [
  {
    title: "Household Agreement Rate",
    value: "82.4%",
    change: "+6.8% this month",
    detail: "Families aligned after Saathi call + Parent Portal review",
    trend: "up",
  },
  {
    title: "Pending Family Callbacks",
    value: "14 Families",
    change: "Avg response < 45 mins",
    detail: "High priority: Dialect-matched senior counsellors assigned",
    trend: "neutral",
  },
  {
    title: "Top Source of Resistance",
    value: "Course Fee & Safety",
    change: "46% of parent hesitations",
    detail: "Addressed via Govt ITI scholarship + PPE safety facts",
    trend: "down",
  },
  {
    title: "Govt ITI Verification Visits",
    value: "128 Scheduled",
    change: "+24% week-on-week",
    detail: "Parent accompanied center tours confirmed",
    trend: "up",
  },
];

export const initialFamilyLeads: FamilyCallbackLead[] = [
  {
    id: "lead_1",
    studentName: "Mohit Verma",
    parentName: "Dinesh Verma (Father)",
    relation: "father",
    phone: "+91 98350 11234",
    preferredDialect: "Bhojpuri / Hindi",
    location: "Muzaffarpur, Bihar",
    targetTrade: "Automobile & EV Service Mechanic",
    govtFee: "₹2,000 / year",
    sentimentLevel: "hesitant",
    primaryResistance: "Father believes ITI mechanic is greasy/dirty work with no growth.",
    aiTranscriptSnippet:
      "Father asked Saathi: 'Is there a permanent job in EV or only roadside garage?' Saathi explained EV diagnostic centers.",
    requestedAt: "10 mins ago",
    status: "pending",
    assignedCounsellor: "Priya Sharma",
  },
  {
    id: "lead_2",
    studentName: "Pooja Kumari",
    parentName: "Sunita Devi (Mother)",
    relation: "mother",
    phone: "+91 94310 88765",
    preferredDialect: "Maithili / Hindi",
    location: "Darbhanga, Bihar",
    targetTrade: "Hospital General Duty Assistant (Nursing)",
    govtFee: "₹3,000 / year",
    sentimentLevel: "conflicted",
    primaryResistance: "Mother worried about night shifts and travel safety on local bus.",
    aiTranscriptSnippet:
      "Mother listened to audio: 'Will my daughter have to work night shifts alone?' Saathi clarified daycare shifts.",
    requestedAt: "35 mins ago",
    status: "pending",
    assignedCounsellor: "Rajeshwar Pandey",
  },
  {
    id: "lead_3",
    studentName: "Vikram Yadav",
    parentName: "Ramakant Yadav (Father)",
    relation: "father",
    phone: "+91 98711 22345",
    preferredDialect: "Hindi / Bhojpuri",
    location: "Patna Rural, Bihar",
    targetTrade: "Electrician & Solar Technician",
    govtFee: "₹1,500 / year",
    sentimentLevel: "aligned",
    primaryResistance: "Needs clarification on how ₹1,000/mo DBT scholarship will be credited.",
    aiTranscriptSnippet:
      "Father reviewed 1-page summary: 'Is Aadhaar bank seeding mandatory before merit list?'",
    requestedAt: "2 hours ago",
    status: "in_progress",
    assignedCounsellor: "Priya Sharma",
    counsellorNotes: "Explained Aadhaar NPCI link for Direct Benefit Transfer. Scheduled ITI visit on Monday.",
  },
  {
    id: "lead_4",
    studentName: "Anjali Sahu",
    parentName: "Santosh Sahu (Father)",
    relation: "father",
    phone: "+91 91234 56780",
    preferredDialect: "Hindi",
    location: "Ranchi, Jharkhand",
    targetTrade: "Computer Operator (COPA) & Junior Accounts",
    govtFee: "₹2,500 / year",
    sentimentLevel: "aligned",
    primaryResistance: "Concerned about whether 12th Arts student can handle GST accounting.",
    aiTranscriptSnippet:
      "Student asked about Tally training. Counsellor demonstrated non-math curriculum structure.",
    requestedAt: "Yesterday",
    status: "resolved",
    assignedCounsellor: "Anita Soren",
    counsellorNotes: "Spoke in regional Hindi. Father confirmed admission fee deposit at ITI Ranchi.",
  },
];

export const initialEditableTrades: TradeEditorItem[] = [
  {
    id: "electrician",
    title: "Electrician & Solar Technician",
    category: "Electrical & Solar",
    govtFee: "₹1,500 / year",
    startingPay: "₹14,000 - ₹20,000",
    payGrowth: "₹28,000+ after 2 years",
    nearestCenter: "Govt ITI Main Campus (Patna)",
    placementRate: "88% verified",
    safetyStatus: "100% PPE compliant",
    eligibility: "Class 10th Pass",
  },
  {
    id: "auto_technician",
    title: "Automobile & EV Service Mechanic",
    category: "Auto & Mechanical",
    govtFee: "₹2,000 / year",
    startingPay: "₹13,000 - ₹18,000",
    payGrowth: "₹30,000+ with EV diagnostics",
    nearestCenter: "PMKK Center & Industrial Estate",
    placementRate: "82% verified",
    safetyStatus: "Regulated workshop protocols",
    eligibility: "Class 10th Pass",
  },
  {
    id: "gda_healthcare",
    title: "Hospital General Duty Assistant",
    category: "Healthcare & Care",
    govtFee: "₹3,000 / year",
    startingPay: "₹13,000 - ₹18,000",
    payGrowth: "₹22,000+ in registered hospitals",
    nearestCenter: "District Hospital Skilling Wing",
    placementRate: "92% verified",
    safetyStatus: "Sanitized clinical environment",
    eligibility: "Class 10th Pass",
  },
];
